In [1]:
# CNN algorithm implementation was used from https://www.kaggle.com/code/huseyinndogan/cnn-tumor-classification-with-96-accuracy and adapted a bit
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [2]:
!pip install tensorflow


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import cv2


In [4]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.initializers import HeUniform, GlorotUniform
from sklearn.preprocessing import StandardScaler
import numpy as npa
import matplotlib.pyplot as plt
import pandas as pd
import os
import random
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import GlobalAveragePooling2D, LeakyReLU
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import losses
from sklearn.metrics import classification_report
from tensorflow.keras.preprocessing.image import ImageDataGenerator



### 📌 1. Path Identification

In [13]:
import pathlib
data_dir = pathlib.Path("..") / "brain-tumor-mri-dataset"
train_dir = data_dir / "Training"
test_dir = data_dir / "Testing"


### 📌 2. Data Preprocessing with ImageDataGenerator

In [6]:
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

### 📌 3. Defining Train & Test Folders

In [11]:
train_dir = str(data_dir / "Training") 
test_dir = str(data_dir / "Testing")    

### 📌 4. Define Image Size & Batch Size for Model

In [8]:
batch_size = 32
img_height = 240
img_width = 240

### 📌 5. Loading Training and Test Datasets

In [14]:
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size = (img_height , img_width),
    batch_size= batch_size,
    class_mode = "categorical"
    )

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size = (img_height , img_width),
    batch_size = batch_size,
    class_mode = "categorical"

    )

print(r"Class Label :" , train_generator.class_indices)


Found 5712 images belonging to 4 classes.
Found 1311 images belonging to 4 classes.
Class Label : {'glioma': 0, 'meningioma': 1, 'notumor': 2, 'pituitary': 3}


### DATA PREPROCESSING SUMMARY

🚀 What Does the Code Do in Brief?

* Determines the dataset folder (data_dir).

* Creates an ImageDataGenerator to rescale the images.

* Determines the training (train_dir) and test (test_dir) data paths.

* Resize the images to 240x240 and load them with flow_from_directory().

* Prints the class labels.

### 📌 6.LET'S DEVELOP THE MODEL

In [15]:

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,          
    width_shift_range=0.2,     
    height_shift_range=0.2,    
    shear_range=0.2,           
    zoom_range=0.2,             
    horizontal_flip=True,       
    fill_mode='nearest'       
)

test_datagen = ImageDataGenerator(rescale=1./255)


In [16]:
model = Sequential([
    Conv2D(32 , (5,5) , activation="relu" ,padding="valid", kernel_initializer=HeUniform()),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Conv2D(64 , (5,5) , activation="relu" ,padding="valid", kernel_initializer=HeUniform()),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Conv2D(128 , (5,5) , activation="relu" ,padding="valid", kernel_initializer=HeUniform()),
    MaxPooling2D(2,2),
    BatchNormalization(),

    Flatten(),

    Dense(64 , activation="relu" , kernel_initializer=HeUniform()),
    Dropout(0.2),
    BatchNormalization(),
    Dense(128 , activation="relu" , kernel_initializer=HeUniform()),
    Dropout(0.2),
    BatchNormalization(),
    Dense(256 , activation="relu" , kernel_initializer=HeUniform()),
    Dropout(0.3),
    BatchNormalization(),

    Dense(4 , activation="softmax" , kernel_initializer=GlorotUniform()),

    ])

In [17]:
model.compile(optimizer=Adam(learning_rate=0.0001) , loss="categorical_crossentropy", metrics=["accuracy"])

In [22]:
early_stop = EarlyStopping(patience=3,monitor="val_loss", restore_best_weights=True)

fit = model.fit(train_generator,epochs=10 #(epoch count is reduced due to process length.)
, validation_data=(test_generator) , callbacks=[early_stop])

Epoch 1/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 239s 1s/step - accuracy: 0.9633 - loss: 0.1238 - val_accuracy: 0.9268 - val_loss: 0.2281
Epoch 2/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 288s 2s/step - accuracy: 0.9701 - loss: 0.0917 - val_accuracy: 0.9283 - val_loss: 0.2192
Epoch 3/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 314s 2s/step - accuracy: 0.9645 - loss: 0.0979 - val_accuracy: 0.9504 - val_loss: 0.1462
Epoch 4/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 311s 2s/step - accuracy: 0.9777 - loss: 0.0707 - val_accuracy: 0.9588 - val_loss: 0.1391
Epoch 5/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 315s 2s/step - accuracy: 0.9794 - loss: 0.0625 - val_accuracy: 0.9603 - val_loss: 0.1392
Epoch 6/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 318s 2s/step - accuracy: 0.9877 - loss: 0.0426 - val_accuracy: 0.9481 - val_loss: 0.1904
Epoch 7/10
179/179 ━━━━━━━━━━━━━━━━━━━━ 317s 2s/step - accuracy: 0.9840 - loss: 0.0603 - val_accuracy: 0.9344 - val_loss: 0.2256


In [23]:
model.save("brain_tumor_model.keras")


In [24]:
model = tf.keras.models.load_model("brain_tumor_model.keras")


In [ ]:
### LET'S TEST ON INPUT IMAGE 

In [25]:
def predict_image(image_path, model):
    img = cv2.imread(image_path)  # Image loading
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Change image color to rgb
    img = cv2.resize(img, (240, 240))  # Change the size of image to fit the model
    img = img / 255.0  # Normalise
    img = npa.expand_dims(img, axis=0) 

    prediction = model.predict(img)  # Predict image 
    predicted_class = npa.argmax(prediction)  # Get predicted image class - from 0 to 3

    class_labels = {0: "Glioma", 1: "Meningioma", 2: "No Tumor", 3: "Pituitary Tumor"}
    return class_labels[predicted_class]  # Get the name of LABEL 

image_path = "brain-tumor-mri-dataset/test-glioma.jpg"  
result = predict_image(image_path, model) # func call
print(f"Предсказанный класс: {result}")


error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


# LET'S EVALUATE THE MODEL

In [26]:

from sklearn.metrics import precision_score, recall_score, f1_score

x_test, y_test = next(test_generator)  


predictions = model.predict(x_test)


predicted_classes = np.argmax(predictions, axis=1)
true_classes = np.argmax(y_test, axis=1)

print(f"Accuracy: { accuracy_score(true_classes, predicted_classes) * 100:.2f}%")
print(f"Precision: {precision_score(true_classes, predicted_classes, average='weighted') * 100:.2f}%")
print(f"Recall: {recall_score(true_classes, predicted_classes, average='weighted') * 100:.2f}%")
print(f"F1 Score: {f1_score(true_classes, predicted_classes, average='weighted') * 100:.2f}%")
print("Confusion Matrix:")
print(confusion_matrix(true_classes, predicted_classes))


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 693ms/step
Accuracy: 96.88%
Precision: 97.22%
Recall: 96.88%
F1 Score: 96.82%
Confusion Matrix:
[[ 5  1  0  0]
 [ 0  8  0  0]
 [ 0  0  8  0]
 [ 0  0  0 10]]


* If you get an error, you can check the code below.

In [16]:

'''

all_predictions = []
all_true_classes = []


for x_batch, y_batch in test_generator:
    predictions = model.predict(x_batch)
    predicted_classes = np.argmax(predictions, axis=1)
    true_classes = np.argmax(y_batch, axis=1)
    

    all_predictions.extend(predicted_classes)
    all_true_classes.extend(true_classes)


print("Accuracy:", accuracy_score(all_true_classes, all_predictions))
print("Classification Report:")

print(classification_report(all_true_classes, all_predictions))

print("Confusion Matrix:")
print(confusion_matrix(all_true_classes, all_predictions))


'''



'\n\nall_predictions = []\nall_true_classes = []\n\n\nfor x_batch, y_batch in test_generator:\n    predictions = model.predict(x_batch)\n    predicted_classes = np.argmax(predictions, axis=1)\n    true_classes = np.argmax(y_batch, axis=1)\n    \n\n    all_predictions.extend(predicted_classes)\n    all_true_classes.extend(true_classes)\n\n\nprint("Accuracy:", accuracy_score(all_true_classes, all_predictions))\nprint("Classification Report:")\n\nprint(classification_report(all_true_classes, all_predictions))\n\nprint("Confusion Matrix:")\nprint(confusion_matrix(all_true_classes, all_predictions))\n\n\n'

### I hope it was useful for you.